### ISSUE TITLE
[타이머화면] data 레이어에 대한 테스트 코드

### ISSUE THREAD

**Issue by nosorae** [nosorae/Muntam-android#21]
## TODO
- [ ] QuestionDao - getQuestions 테스트
- [ ] QuestionDao - getQuestionExamId 테스트
- [ ] QuestionDao - getQuestionById 테스트
- [ ] QuestionDao -  updateQuestion 테스트
- [ ] ExamDao - getExam 테스트

*주의점은 테스트할 때는 id auto gennerate 안하는 게 편하다..
