### ISSUE TITLE
[파이어베이스] 세팅, 로그 남기기

### ISSUE THREAD

**Issue by nosorae** [nosorae/Muntam-android#55]
## TODO
- [ ] 세팅
- [ ] 여러군데 로그 남기기 (정보성, 에러로그)
- [ ] 과목이름, 시험 이름 저장
- [ ] 광고로드 실패에 로그
- [ ]
