### ISSUE TITLE
[QA] 지속 수정

### ISSUE THREAD

**Issue by nosorae** [nosorae/Muntam-android#57]
## TODO
- [x] 일단 시험이 종료되면 다른 상태로 업데이트 못하게 방어코드 작성
- [x] 시험리스트화면에서 광고까지 고려해서 넘기기 (광고안봤으면 보여주고 넘겨)
- [x] 시험 리스트화면에서 초과시간 보여주기
- [x] 시험리스트화면에서 없는 경우 보여주기
- [x] 과목리스트화면에서 마지막에 본 시험 보여줘
- [x] 문제리스트 화면에서 알림 설정하다보면 소팅 잘 안되는 경우 있음
- [x] 이모지 더 채워넣고 정상적으로 안나오는 건 빼기
- [x] 과목삭제하면 시험이랑 문제도 다 삭제하기 (알림 예약도 지우기)
- [x] 시험 삭제하면 문제도 다 삭제하기 (알림 예약도 지우기)
- [x] 엔티티 업데이트 할 때 modified_at 채우기
- [x] 즐겨찾기 화면 토스트 위로 나오는 버그
- [x] READY 상태에서 나갔다 들어오면 터짐 (READY 일 때 일시정지 못하게 막기..?)
- [x] 광고 로드 실패한 경우 예외처리
- [x] 문제 엔티티 생성할 때 기본으로 맞은문제로 처리
- [x] 딥링크 적용
- [x] 스테이터스바 색깔
- [x] 긴급공지 빈 텍스트면 안나오게 설정
- [x]  timeLimit 을 초단위로 바꾸기
- [x] 13 은 알림 권한 얻어오기
- [x] 바텀시트 뒤로가기 막기
