### ISSUE TITLE
[백로그] 지속 수정

### ISSUE THREAD

**Issue by nosorae** [nosorae/Muntam-android#63]
## TODO
- [ ] 주기적으로 시험보라고 알림 주기 (ex. ~일동안 시험보지 않으셨네요, 실전시험 기록하세요)
- [ ] 백그라운드에서도 돌게하거나 넷플릭스처럼 작은 창으로 나오게하는 거
- [ ] 시험 만들 때 문제에 대한 정보 적을 수 있게 (ex 10번 - 주의하기)
- [ ] 구글로그인 + 기기옮겨도 데이터 옮기기 가능
- [ ] 다크모드
- [ ] 다양한 시험흐름 분석
- [ ] 일시정지 문제도 다시 기록할 수 있게 수정
- [ ] 인앱리뷰
